### ISSUE TITLE
Not able to find model

### ISSUE THREAD

**Issue by Nitwel** [mallorbc/stable-diffusion-klms-gui#2]
While trying to start the image, it is not able to locate the model file. I'm not sure if this is something WSL specific but the file does exist with the proper `model.ckpt`.

```
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Traceback (most recent call last):
  File "/app/scripts/web_gui.py", line 352, in <module>
    model = load_model_from_config(config, opt.ckpt)
  File "/app/scripts/web_gui.py", line 121, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/ldm/stable-diffusion-v1/model.ckpt'
```

```
nitwel@Nils-PC:~/Dev/StableDiffusion/stable-diffusion-klms-gui$ ls -l
total 160
-rw-r--r-- 1 nitwel nitwel 34523 Sep  7 10:02 LICENSE
-rw-r--r-- 1 nitwel nitwel 13614 Sep  7 10:02 README.md
-rw-r--r-- 1 nitwel nitwel  9344 Sep  7 10:02 Stable_Diffusion_v1_Model_Card.md
drwxr-xr-x 3 nitwel nitwel  4096 Sep  7 10:02 assets
drwxr-xr-x 6 nitwel nitwel  4096 Sep  7 10:02 configs
drwxr-xr-x 4 nitwel nitwel  4096 Sep  7 10:02 data
drwxr-xr-x 2 nitwel nitwel  4096 Sep  7 10:26 diffusion_model
drwxr-xr-x 2 nitwel nitwel  4096 Sep  7 10:02 docker
-rw-r--r-- 1 nitwel nitwel   734 Sep  7 10:02 environment.yaml
drwxr-xr-x 3 nitwel nitwel  4096 Sep  7 10:02 frontend
drwxr-xr-x 5 nitwel nitwel  4096 Sep  7 10:02 ldm
drwxr-xr-x 2 nitwel nitwel  4096 Sep  7 10:10 log
-rw-r--r-- 1 nitwel nitwel 28175 Sep  7 10:02 main.py
drwxr-xr-x 4 nitwel nitwel  4096 Sep  7 10:02 models
-rw-r--r-- 1 nitwel nitwel 10099 Sep  7 10:02 notebook_helpers.py
drwxr-xr-x 2 nitwel nitwel  4096 Sep  7 10:02 outputs
-rwxr-xr-x 1 nitwel nitwel   202 Sep  7 10:23 run_image.sh
drwxr-xr-x 3 nitwel nitwel  4096 Sep  7 10:02 scripts
-rw-r--r-- 1 nitwel nitwel   233 Sep  7 10:02 setup.py
nitwel@Nils-PC:~/Dev/StableDiffusion/stable-diffusion-klms-gui$ cd diffusion_model/
nitwel@Nils-PC:~/Dev/StableDiffusion/stable-diffusion-klms-gui/diffusion_model$ ls -l
total 4165416
-rw-r--r-- 1 nitwel nitwel 4265380512 Sep  7 10:07 model.ckpt
```

**Comment by isieo** [comment]
are you using mingw on windows?
you might want to add the env variable
MSYS_NO_PATHCONV=1

**Comment by Nitwel** [comment]
I don't think so. And maybe the issue is somewhere else as I think I get no error actually.
This is all I get and then it terminates.
```
nitwel@Nils-PC:~/Dev/StableDiffusion/stable-diffusion-klms-gui$ docker run --rm -p 7860:7860 --gpus all -e MSYS_NO_PATHCONV=1 -v `pwd`/diffusion_model:/app/models/ldm/stable-diffusion-v1/ -v `pwd`/outputs:/app/outputs --name stable_diffusion --ipc host stable_diffusion
/usr/local/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth" to /app/gfpgan/weights/detection_Resnet50_Final.pth

100%|██████████| 104M/104M [00:04<00:00, 25.3MB/s]
  0%|          | 0.00/81.4M [00:00<?, ?B/s]Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.2.2/parsing_parsenet.pth" to /app/gfpgan/weights/parsing_parsenet.pth

100%|██████████| 81.4M/81.4M [00:02<00:00, 32.9MB/s]
```

**Comment by Sassogamer2** [comment]
I'm having the same exact issue, it downloads parsing_parsenet.pth and then stops (running on WSL2)

**Comment by isieo** [comment]
not docker's env your shell's env

try 
```
export MSYS_NO_PATHCONV=1

docker run --rm -p 7860:7860 --gpus all  -v `pwd`/diffusion_model:/app/models/ldm/stable-diffusion-v1/ -v `pwd`/outputs:/app/outputs --name stable_diffusion --ipc host stable_diffusion

```

**Comment by Nitwel** [comment]
Tried that but didn't change anything. I'm pretty sure that it does find the file now as I messed other stuff up before to get that error message. Now it's just downloading stuff, than exiting without any error message or log.

**Comment by jamesmckee7** [comment]
Hi Nitwel I faced the same issue. I belive it's due to the run_image.sh file being configured for use on linux. As such the 'pwd' command in setting up the docker volumes is not returning the directory correctly. You can resolve this by changing the `pwd` to /$(pwd) in the run_image.sh file. The run_image.sh file should then look like this
```
`#!/bin/bash
mkdir -p ./log
docker run --rm -p 7860:7860 --gpus all -v /$(pwd)/diffusion_model:/app/models/ldm/stable-diffusion-v1/ -v /$(pwd)/outputs:/app/outputs --name stable_diffusion --ipc host stable_diffusion 
`
```

**Comment by Nitwel** [comment]
Didn't work either.
I'll close that issue as it is missleading and the above error was caused by me testing something out and is not actually related to any of this. I'll create a new Issue with all the details that are important.

**Comment by Xaymar** [comment]
Ran into this exact issue with WSL2 and Docker-on-WSL2, with the same file missing. Unfortunately it was not documented what exactly solved the problem, so I'm a bit stuck. Anything I should try that isn't already in this thread?

**Comment by Xaymar** [comment]
Ended up solving this by adding this to the Dockerfile just before `CMD [ "python", "scripts/web_gui.py" ]`:

```
EXPOSE 7860:7860
VOLUME ["/app/outputs"]
COPY ["diffusion_model/model.ckpt", "/app/models/ldm/stable-diffusion-v1/model.ckpt"]
``` 

and modifying both build scripts to use `-f docker/Dockerfile` and then running the scripts outside of the docker directory.
